### ISSUE TITLE
Sacerdote Sombras

### ISSUE THREAD

**Issue by MJElettra** [Myst/Bugtracker434#2]
Palabra de sombras muerte: (hechizo) ID: 32379

Hace un daño 25% superior a lo normal.

Peste deboradora mejorada: (Talento):  ID: 63626

Al aplicar la peste deboradora, esta hace u daño muy exagerado. Un 30% superior a lo normal.

orbes de las sombras: ID: 95740

Estos Orbes se acumulan con normalidad, pero al usar los respectivos hechizos para gastarlos, estos se consumen pero no aumentan el daño. Lo que ahce que la maestria en esta clase sea totalmente inutil.

Maligno d elas sombras: ID: 34433

Cuando esta mascota hace daño repone el doble de mana de lo normal.

**Comment by Myst** [comment]
Reparado.
