### ISSUE TITLE
Bug DE Hermandad

### ISSUE THREAD

**Issue by elianbhh123** [Myst/Bugtracker434#3]
Buenas Les escribe El lider De la hermadnad "Gladiadorez The azeroth" -Lothars
Desde que cree mi hermandad he visto que ni la reputacion de la hermandad no me sube y que los logros de la hermandad no estan funcionando
Espero que resuelvan esto, gracia por su atencion Att/ Lothars

**Comment by Myst** [comment]
Ya fue reparado.
